/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CusData: typeof import('./src/components/CusData/index.vue')['default']
    CusEmpty: typeof import('./src/components/CusEmpty/index.vue')['default']
    CusLang: typeof import('./src/components/CusLang/index.vue')['default']
    CusList: typeof import('./src/components/CusList/index.vue')['default']
    CusNav: typeof import('./src/components/CusNav/index.vue')['default']
    CusPicker: typeof import('./src/components/CusPicker/index.vue')['default']
    CusPop: typeof import('./src/components/CusPop/index.vue')['default']
    CusProgress: typeof import('./src/components/CusProgress/index.vue')['default']
    Demo: typeof import('./src/components/CusLang/demo.vue')['default']
    Line: typeof import('./src/components/Line/index.vue')['default']
    LineCard: typeof import('./src/components/LineCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./src/components/Title/index.vue')['default']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
