/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CusDate: typeof import('./src/components/CusDate/index.vue')['default']
    CusEmpty: typeof import('./src/components/CusEmpty/index.vue')['default']
    CusLang: typeof import('./src/components/CusLang/index.vue')['default']
    CusLoading: typeof import('./src/components/CusLoading/index.vue')['default']
    CusNav: typeof import('./src/components/CusNav/index.vue')['default']
    CusPicker: typeof import('./src/components/CusPicker/index.vue')['default']
    CusProgress: typeof import('./src/components/CusProgress/index.vue')['default']
    CusTab: typeof import('./src/components/CusTab/index.vue')['default']
    CusTitle: typeof import('./src/components/CusTitle/index.vue')['default']
    Demo: typeof import('./src/components/CusLang/demo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShinyBtn: typeof import('./src/components/VueBits/ShinyBtn.vue')['default']
    ShinyText: typeof import('./src/components/VueBits/ShinyText.vue')['default']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VueBits: typeof import('./src/components/VueBits/index.vue')['default']
  }
}
